# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-10 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('keterangan', models.TextField()),
                ('gambar', models.ImageField(upload_to='')),
                ('waktu', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
