# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-12 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_postmodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='keterangan',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='nama',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='category',
            field=models.CharField(choices=[('Pneumonia', 'pneumonia'), ('Tuberculosis', 'tuberculosis'), ('Covid19', 'covid19'), ('Normal', 'normal')], default='database', max_length=100),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
