# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-14 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20220714_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='gambar',
            field=models.FileField(blank=True, null=True, upload_to='database/images'),
        ),
    ]
