# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-01 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20220727_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='waktu_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='category',
            field=models.CharField(choices=[('Pneumonia', 'Pneumonia'), ('Tuberculosis', 'Tuberculosis'), ('COVID19', 'COVID19'), ('Normal', 'Normal')], max_length=100),
        ),
    ]
